name: Test Nix Quick Install
on:
  workflow_dispatch: {}
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v26
      - run: nix build --version
      - run: nix build ./examples/flakes-simple
      - name: hello
        run: ./result/bin/hello
      - name: Hello Cow
        run: nix-shell -p cowsay --run cowsay Hello
