name: Test Nix Quick Install
on:
  workflow_dispatch: {}
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v26
      - run: nix build --version
      - run: |
          commit=6723fa4e4f1a30d42a633bef5eb01caeb281adc3 # nixos-23.11 branch from 2024-01-08
          if ! [ -d "nixpkgs-${commit}" ]
          then
            curl --location "https://github.com/NixOS/nixpkgs/archive/${commit}.tar.gz" | tar -xz
          fi
      - name: Hello Cow
        run: |
          export NIX_PATH=nixpkgs="$(pwd)"/nixpkgs-6723fa4e4f1a30d42a633bef5eb01caeb281adc3
          nix-shell -p cowsay --run "cowsay Hello"
